### ISSUE TITLE
License

### ISSUE THREAD

**Issue by usubhash** [inovex/planning-poker#2]
Can you put the license on this please?

**Comment by djungowski** [comment]
I see you have already fixed the login issues. Can you tell what the problem was?

As for the license: Good idea, will do so.

**Comment by usubhash** [comment]
First of all, your app looks great. Nice job.

I did not configure the parameters correctly. But I noticed that after logging in, the application is not working correctly. If I put anything in chat it shows multiple times. Same thing with number of users etc.

**Comment by djungowski** [comment]
Yes, that's a known issue, when using node.js 0.10.x
I haven't found out yet where the problem is, but I hope to fix it asap

**Comment by djungowski** [comment]
I just fixed the "multiple times" bug. It should work if you pull the latest version (there's also a tag 0.4.1 for that). Note that setup.sh has been deleted aswell and replaced by package.json. This means that running "npm install" does all the dependency management!

**Comment by usubhash** [comment]
Awesome. Appreciate your quick fix. 

Can you give permission so that I can reuse some of this code?

**Comment by djungowski** [comment]
Since I wrote most of this code during work time, I will have to check with my employer first. I'll get back to you

**Comment by usubhash** [comment]
Thank you. For some reason, I don’t see the images. Also, how do you flip the cards?

**Comment by djungowski** [comment]
You mean you don't see any images? Can you make a screenshot?

Only the Scrum Master can flip the cards. He is the one moderating. To enter User Stories a Product Owner has to sign-in. Which is a good point, a how-to would be nice indeed.

**Comment by usubhash** [comment]
I noticed that in the HTML you are not using the port information. I had to add it and after that it works fine. Flip works good. Thanks. Latest commit cause login not to work. 

Did you get a chance to finalize on the license?

**Comment by djungowski** [comment]
Yes, I did. The LICENSE is now included in the git repo.

Thanks for the information on the port, I just opened issue #3 for that

**Comment by netsky1** [comment]
Hey will this work on ubuntu 12.04 x32 and also be configured to use worldcoin without changing any proprietary code?

**Comment by djungowski** [comment]
Planning Poker is an estimation technique and has not much in common with regular poker. See also http://en.m.wikipedia.org/wiki/Planning_poker for reference.
